name: chula
images_dir: [Path to WBC 5000 dir]
train_labels_path: [Path to labels_train.csv]
test_labels_path: [Path to labels_test.csv]
num_classes: 8 # Adjust to match the number of classes
classes:
- "SNE"
- "Lymphocyte"
- "Monocyte"
- "BNE"
- "Eosinophil"
- "Myeloblast"
- "Basophil"
- "Metamyelocyte"
# - "Myelocyte"
# - "Atypical Lymphocyte"
# - "Promyelocyte"
# - "Monoblast"
# - "Smudge Cell"    
# - "Lymphoblast"
# - "Giant Platelet"